// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWUv8G9xHiwi8ceQfXDDm-V9G73k2A1sk',
    appId: '1:380101128497:web:e115a441b25e13417dc010',
    messagingSenderId: '380101128497',
    projectId: 'bonyan-69932',
    authDomain: 'bonyan-69932.firebaseapp.com',
    storageBucket: 'bonyan-69932.appspot.com',
    measurementId: 'G-XD3LNYCGV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcaYLH8JBkgRohSv3-P3-6ZJma_KXY0Dk',
    appId: '1:380101128497:android:fd37349641aa82c57dc010',
    messagingSenderId: '380101128497',
    projectId: 'bonyan-69932',
    storageBucket: 'bonyan-69932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArtkivdYdtVMKOSIe9Ar1wwUWqYBiNpEs',
    appId: '1:380101128497:ios:28c5352c69221ea17dc010',
    messagingSenderId: '380101128497',
    projectId: 'bonyan-69932',
    storageBucket: 'bonyan-69932.appspot.com',
    androidClientId: '380101128497-rdpa2llnssksr0uk013ia06rorphcull.apps.googleusercontent.com',
    iosClientId: '380101128497-okr9ho521a6v2mj71hqf1ugrms3v9rce.apps.googleusercontent.com',
    iosBundleId: 'com.bonyan.bonyan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArtkivdYdtVMKOSIe9Ar1wwUWqYBiNpEs',
    appId: '1:380101128497:ios:28c5352c69221ea17dc010',
    messagingSenderId: '380101128497',
    projectId: 'bonyan-69932',
    storageBucket: 'bonyan-69932.appspot.com',
    androidClientId: '380101128497-rdpa2llnssksr0uk013ia06rorphcull.apps.googleusercontent.com',
    iosClientId: '380101128497-okr9ho521a6v2mj71hqf1ugrms3v9rce.apps.googleusercontent.com',
    iosBundleId: 'com.bonyan.bonyan',
  );
}
